"""empty message

Revision ID: 1c3dc1b91f10
Revises: a1534c6b4556
Create Date: 2023-09-30 18:20:57.735986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3dc1b91f10'
down_revision = 'a1534c6b4556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('learning_goal', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('learning_goal')
        batch_op.drop_column('grade')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
