"""empty message

<<<<<<<< HEAD:migrations/versions/14ee9ecdae58_.py
Revision ID: 14ee9ecdae58
Revises: 
Create Date: 2023-11-05 11:25:04.936250
========
Revision ID: 482ae5b78e7b
Revises: 
Create Date: 2023-11-14 00:54:39.472630
>>>>>>>> questionReducer:migrations/versions/482ae5b78e7b_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/14ee9ecdae58_.py
revision = '14ee9ecdae58'
========
revision = '482ae5b78e7b'
>>>>>>>> questionReducer:migrations/versions/482ae5b78e7b_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('learning_goal', sa.String(length=255), nullable=True),
    sa.Column('subscription_start_date', sa.Date(), nullable=True),
    sa.Column('subscription_end_date', sa.Date(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
